import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased bg-gray-300 w-screen py-8 min-h-screen flex`}
      >
        <div className="max-w-[640px] mx-auto px-4 py-8 bg-gray-100 rounded-lg shadow-lg flex-1">
          {children}
        </div>
      </body>
    </html>
  );
}
